### ISSUE TITLE
URL resolution not working on 1Channel 2.1.0 and Frodo on a RPi

### ISSUE THREAD

**Issue by brainstorm** [bstrdsmkr/1Channel#96]
After an update to 1Channel, there seems to be a problem with 1channel and XBMC url resolver, here are the offending lines according to debug (I've added three additional log lines):

```
def PlaySource(url, title, img, year, imdbnum, video_type, season, episode, strm=False):
    try: _1CH.log('Attempting to play url: %s' % url)
(...)

    _1CH.log("STREAM URL FOR THE CURRENT MOVIE IS: %s" % stream_url)
    _1CH.log("Methods of last object are: %s" % dir(stream_url))
    _1CH.log("Error message from urlresolver: %s" % stream_url.msg)

    listitem.setPath(stream_url)
    xbmcplugin.setResolvedUrl(int(sys.argv[1]), True, listitem)
```

And the debug log itself. It fails for all movies.

```
16:07:55 T:3046806032   DEBUG: Loading: /usr/lib/xbmc/system/ImageLib-arm.so
16:07:55 T:2739606624  NOTICE: 1Channel: STREAM URL FOR THE CURRENT MOVIE IS: <urlresolver.plugnplay.interfaces.unresolvable instance at 0x3d7d260>
16:07:55 T:2739606624  NOTICE: 1Channel: Methods of last object are: ['__doc__', '__init__', '__module__', '__nonzero__', 'code', 'msg']
16:07:55 T:2739606624  NOTICE: 1Channel: Error message from urlresolver: 'NoneType' object has no attribute 'group'
16:07:55 T:2739606624   ERROR: EXCEPTION: argument "path" for method "setPath" must be unicode or str
16:07:55 T:2739606624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument "path" for method "setPath" must be unicode or str
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.1channel/default.py", line 2628, in <module>
                                                PlaySource(url, title, img, year, imdbnum, video_type, season, episode)
                                              File "/storage/.xbmc/addons/plugin.video.1channel/default.py", line 593, in PlaySource
                                                listitem.setPath(stream_url)
                                            TypeError: argument "path" for method "setPath" must be unicode or str
                                            -->End of Python script error report<--
16:07:56 T:2739606624    INFO: Python script stopped
16:07:56 T:2739606624   DEBUG: Thread XBPyThread 2739606624 terminating
16:07:56 T:3046806032   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
16:07:56 T:3046806032   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.1channel/?episode=&img=http%3A%2F%2Fia.media-imdb.com%2Fimages%2FM%2FMV5BODYwNDYxNDk1Nl5BMl5BanBnXkFtZTgwOTAwMTk2MDE%40._V1_SX300.jpg&title=A+title+of+a+movie&url=http%3A%2F%2Fwww.movshare.net%2Fvideo%2Fad076644477e&season=&imdbnum=tt0359888&video_type=movie&mode=PlaySource&year=2013]
16:07:56 T:3046806032   DEBUG: Playlist Player: one or more items failed to play... aborting playback
```
